.Dd October 12, 2013
.Dt olecfinfo
.Os libolecf
.Sh NAME
.Nm olecfinfo
.Nd determines information about a Object Linking and Embedding (OLE) Compound File (CF)
.Sh SYNOPSIS
.Nm olecfinfo
.Op Fl c Ar codepage
.Op Fl ahvV
.Va Ar source
.Sh DESCRIPTION
.Nm olecfinfo
is a utility to determine information about a Object Linking and Embedding (OLE) Compound File (CF)
.Pp
.Nm olecfinfo
is part of the
.Nm libolecf
package.
.Nm libolecf
is a library to access the Object Linking and Embedding (OLE) Compound File (CF) format
.Pp
.Ar source
is the source file.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl a
shows allocation information
.It Fl c Ar codepage
specify the codepage of ASCII strings, options: ascii, windows-874, windows-932, windows-936, windows-949, windows-950, windows-1250, windows-1251, windows-1252 (default), windows-1253, windows-1254, windows-1255, windows-1256, windows-1257 or windows-1258
.It Fl h
shows this help
.It Fl v
verbose output to stderr
.It Fl V
print version
.El
.Sh ENVIRONMENT
None
.Sh FILES
None
.Sh EXAMPLES
.Bd -literal
# olecfinfo WordDocument.doc
olecfinfo 20131012

OLE Compound File information:
	Version			: 3.62
	Sector size		: 512
	Short sector size	: 64

Storage and stream items:
Root Entry (768 bytes)
  1Table (42656 bytes)
  WordDocument (4096 bytes)
  \x05SummaryInformation (4096 bytes)
  \x05DocumentSummaryInformation (4096 bytes)
  \x01CompObj (114 bytes)

Summary information:
.Dl        ...

.Ed
.Sh DIAGNOSTICS
Errors, verbose and debug output are printed to stderr when verbose output \-v is enabled.
Verbose and debug output are only printed when enabled at compilation.
.Sh BUGS
Please report bugs of any kind to <joachim.metz@gmail.com> or on the project website:
https://github.com/libyal/libolecf/
.Sh AUTHOR
These man pages were written by Joachim Metz.
.Sh COPYRIGHT
Copyright (C) 2008-2017, Joachim Metz <joachim.metz@gmail.com>.
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.Sh SEE ALSO
.Xr olecfexport 1
